### ISSUE TITLE
support lock_time

### ISSUE THREAD

**Issue by ecdsa** [trezor/python-trezor#106]
does the API allow to pass a lock_time?
I did not find it in the code

**Comment by prusnak** [comment]
`SignTx` message supports passing `version` and `lock_time` attributes.

https://github.com/trezor/trezor-common/blob/master/protob/messages.proto#L559

They were just not exposed by sign_tx function in the API.

Fixed in https://github.com/trezor/python-trezor/commit/504db8283b767db734d62efe8b5e8b7a00a88aba

Thanks!

(I also bumped version to 0.7.13 and uploaded it to PyPI).

**Comment by ecdsa** [comment]
thanks
