### ISSUE TITLE
get_transport must succeed in order to access command usage

### ISSUE THREAD

**Issue by saleemrashid** [trezor/python-trezor#123]
This prevents command usage being accessed if no TREZOR is connected or the TREZOR is not accessible.

## Steps to reproduce

1. Disconnect all TREZOR devices
2. `trezorctl get_address --help`

## Expected result

`get_address` usage information

## Actual result

```
Exception:  Device not found
```

**Comment by prusnak** [comment]
I think this would be best fixed as a major rewrite of transports (i.e. transport opens connection only when needed = before send and not when it is instantiated).

I tried to fix trezorctl meanwhile until we'll do this, but I did not find any solution that is not very hackish/ugly. :-/

**Comment by saleemrashid** [comment]
@prusnak I think that RAII makes sense for the transports

**Comment by prusnak** [comment]
The current architecture does not really make sense, frankly.

Some time ago, Jan tried to refactor it (branch https://github.com/trezor/python-trezor/tree/transport-connection), I even pushed it further (branch https://github.com/trezor/python-trezor/tree/protocol-device). But the development stalled because of other work to do.

In the future, I'd like to do something similar to `protocol-device` branch, because all you should care about is some kind of high-level USBDevice/BridgeDevice object, not some stuff transports/protocols/etc. underneath.

**Comment by saleemrashid** [comment]
@prusnak Agreed. Devices as non-RAII, but transports as RAII, makes sense.

**Comment by jpochyla** [comment]
Should be fixed in master, closing?

**Comment by saleemrashid** [comment]
@jpochyla ACK
