### ISSUE TITLE
Code request: implement a simple command which lists all UTXOs of a particular coin

### ISSUE THREAD

**Issue by yashbhutwala** [trezor/python-trezor#213]
How can I see all UTXOs associated with my Trezor device?

**Comment by prusnak** [comment]
You can't at the moment. This would require implementing wallet logic in
python-trezor and that's not the focus of this communication library.

**Comment by saleemrashid** [comment]
Basically, you want to follow the BIP-32 account discovery (either using multiple calls of `client.get_address` or a single call of `client.get_public_node` and using `trezorlib.ckd_public` to derive the addresses for more efficiency). You would need to implement a way for getting a list of UTXOs for these address (e.g. calling out to an ElectrumX server or a Bitcoin API).

If you don't need to do this programmatically, you could simply use Electrum and coin control.

**Comment by yashbhutwala** [comment]
Thanks @saleemrashid. @prusnak, perhaps a feature to be added to Trezor in the future? It'd be nice to be able to see utxos for consolidation purposes.

**Comment by prusnak** [comment]
We might consider adding basic functions like UTXO discovery in this repo in the future. But I would rather not got further than this and re-implement the whole wallet here.

Let's keep this opened as a reminder.

**Comment by saleemrashid** [comment]
We could simply add a method `list_unspent` to `TxApi` and an implementation of BIP-32 account discovery that takes a `HDNodeType` and a `TxApi`.

**Comment by prusnak** [comment]
I like this approach.

**Comment by saleemrashid** [comment]
> We could implement a BIP44-like "walk addresses" algorithm, but this would be better placed in some sort of separate tool.

Perhaps, but we already have `ckd_public` and it could be implemented under there. If you plan to move `ckd_public` though, we could implement it wherever that is moved to.

> Even the fact that `trezorctl` supports `tx_api` seems mostly incidental to what it actually does.

Agreed, but this should be trivial to add for most currently supported APIs.

**Comment by matejcik** [comment]
> Perhaps, but we already have `ckd_public` and it could be implemented under there.

I disagree. Mainly because "walk address" algorithm requires a backend for querying transactions, that's the stop condition, otherwise you iterate over addresses forever. I don't think backend querying belongs in trezorlib at all. Hence, separate tool.
(The presence of `ckd_public` is questionable as well, it will probably dissolve when I get to refactoring this part of the code.)

Anyway you're generally right that this would not be hard to implement in the current code. My point is that the current code isn't very well structured and that is something to be fixed first, before adding non-core features to it.

**Comment by matejcik** [comment]
closing this bug, the feature will be instead supported in microwallet
