### ISSUE TITLE
Unbundle protobuf-json

### ISSUE THREAD

**Issue by hegjon** [trezor/python-trezor#86]
protobuf_json.py is copied from the protobuf-json library, it would improve packages for Linux distros to unbundle it.

For more details:

- https://fedoraproject.org/wiki/Bundled_Libraries?rd=Packaging:Bundled_Libraries
- https://www.debian.org/doc/debian-policy/ch-source.html#s-embeddedfiles
- http://pycon.blip.tv/file/2072580/

I understand that this issue is inter-project and will involve changes in protobuf-json that enables it to be published to the Python Package Index.

**Comment by prusnak** [comment]
We are using a patched version of protobuf_json that uses `hexlify` instead of `encode('string_escape')` for serializing `bytes`.

I don't think we'll do the unbundling unless:
a) protobuf_json is published to PyPI
b) it allows easy configuration of callbacks hardcoded in `_ftype2js` and `_js2ftype`: https://github.com/dpp-name/protobuf-json/blob/master/protobuf_json.py#L109-L147

**Comment by hegjon** [comment]
Thanks for your feedback, I included this ticket as a comment in the RPM package for Fedora

**Comment by prusnak** [comment]
At least I tried to minimize the diff between upstream protobuf_json.py and ours version in https://github.com/trezor/python-trezor/commit/725b64bede1f63171002307cd56e0cced135d6e6

**Comment by hegjon** [comment]
Thanks, the python-trezor RPM package for Fedora just got approved
